name: Demo

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up --build -d

      - name: Check running containers
        run: docker ps -a

      - name: Run demo.sh script
        run: ./demo.sh
        shell: bash

      - name: Show container logs
        run: docker-compose logs

      - name: Stop containers
        if: always()
        run: docker-compose down
